pmodels/yaksa

.github/pull_request_template.md
Signed-off-by: Pavan Balaji <balaji@anl.gov>
explicitly mention the CLA in the PR template
=> github: explicitly mention the CLA in the PR template

README.md
Signed-off-by: Pavan Balaji <balaji@anl.gov>
missed a minor cleanup to README.md
=> readme: missed a minor cleanup to README.md

m4/aclocal_cc.m4, src/frontend/pup/yaksa_request.c, src/util/yaksu_atomics.c, src/util/yaksu_atomics.h
Miscellaneous cleanup patches.
=> Miscellaneous cleanup patches

test/runtests.py
* add verbose options for runtests.py, so we can see more what's going on.
* check whether we are being redirected and disable color escape output.
=> runtests: some enhancement

test/flatten/Makefile.mk, test/iov/Makefile.mk, test/pack/Makefile.cuda.mk, test/pack/Makefile.mk, test/simple/Makefile.mk
Add sub test targets to allow optional quick testing, for example, `make test-simple`.
=> build: add per dir test target

.github/pull_request_template.md, src/backend/cuda/genpup.py, src/backend/cuda/hooks/yaksuri_cuda_type_hooks.c, src/backend/cuda/include/yaksuri_cuda_post.h, src/backend/cuda/include/yaksuri_cuda_pre.h, src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/md/yaksuri_cudai_md.c, src/backend/cuda/pup/yaksuri_cuda_event.c, src/backend/cuda/stub/yaksuri_cuda_post.h, src/backend/cuda/stub/yaksuri_cuda_pre.h, src/backend/seq/genpup.py, src/backend/seq/hooks/yaksuri_seq_hooks.c, src/backend/seq/include/yaksuri_seq_post.h, src/backend/seq/include/yaksuri_seqi.h, src/backend/src/yaksur_hooks.c, src/backend/src/yaksur_pre.h, src/backend/src/yaksur_pup.c, src/backend/src/yaksur_request.c, src/backend/src/yaksuri.h, src/backend/src/yaksuri_progress.c, src/frontend/include/yaksi.h, test/flatten/Makefile.mk, test/flatten/flatten.c, test/iov/Makefile.mk, test/iov/iov.c, test/pack/Makefile.cuda.mk, test/pack/Makefile.mk, test/pack/pack.c, test/simple/Makefile.mk
This PR includes a set of miscellaneous improvements to yaksa.
=> Miscellaneous improvements

src/backend/seq/include/Makefile.mk, test/Makefile.mk
This PR fixes a couple of broken things in "make dist"
=> Fixes to get "make dist" to work

Makefile.am, examples/Makefile.mk, examples/contig.c, examples/fuf.c, examples/hindexed.c, examples/hindexed_block.c, examples/hvector.c, examples/indexed.c, examples/indexed_block.c, examples/iov.c, examples/matrix_util.c, examples/matrix_util.h, examples/resized.c, examples/subarray.c, examples/vector.c, test/Makefile.mk
=> examples: add examples

test/runtests.py
Include build failures in error logs during make testing.
Fixes pmodels/yaksa#29
=> Include build failures in error logs during make testing

Makefile.am, configure.ac
Allow yaksa to be built as an embedded library, so it can be absorbed into other libraries such as MPICH.
=> Allow for embedded builds

src/backend/src/yaksuri_progress.c
=> progress: silence warning

src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c, src/backend/cuda/include/yaksuri_cuda_post.h, src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/pup/yaksuri_cudai_event.c, src/backend/cuda/pup/yaksuri_cudai_get_ptr_attr.c, src/backend/cuda/pup/yaksuri_cudai_pup.c, src/backend/cuda/stub/yaksuri_cuda_post.h, src/backend/src/yaksur_hooks.c, src/backend/src/yaksur_pre.h, src/backend/src/yaksur_pup.c, src/backend/src/yaksur_request.c, src/backend/src/yaksuri.h, src/backend/src/yaksuri_progress.c
This PR cleans up a number of things in the backend management code to abstract some capabilities from the GPU drivers, and to manage a few things in the glue layer.  This would hopefully make things easier for the Intel GPU code integration in the future.
=> Backend cleanup in preparation for Intel GPU support

_config.yml
This was accidentally created at the start of the project.
=> Remove accidentally created _config.yml file

src/frontend/include/yaksi.h, src/frontend/init/yaksa_init.c, src/frontend/types/yaksa_blkindx.c, src/frontend/types/yaksa_contig.c, src/frontend/types/yaksa_dup.c, src/frontend/types/yaksa_free.c, src/frontend/types/yaksa_indexed.c, src/frontend/types/yaksa_resized.c, src/frontend/types/yaksa_struct.c, src/frontend/types/yaksa_subarray.c, src/frontend/types/yaksa_vector.c
Miscellaneous fixes for type creation and freeing
=> Miscellaneous fixes for type creation and freeing

test/dtpools/src/dtpools_attr.c, test/dtpools/src/dtpools_internal.h, test/pack/pack.c
Miscellaneous warnings squashes.
=> Warning squashes

src/backend/gencomm.py, src/backend/seq/hooks/yaksuri_seq_hooks.c, src/backend/seq/pup/yaksuri_seq_pup.c, src/backend/src/yaksur_hooks.c, src/backend/src/yaksuri_progress.c, src/frontend/include/yaksa.h.in, src/frontend/init/yaksa_init.c, src/frontend/pup/yaksi_iunpack_element.c, src/frontend/types/yaksa_blkindx.c, src/frontend/types/yaksa_contig.c, src/frontend/types/yaksa_indexed.c, src/frontend/types/yaksa_struct.c, src/util/yaksu_pool.c
Fix some of the issues reported by coverity.
=> Coverity fixes

src/util/yaksu_pool.c
Bug fix in the pool element allocation.
=> Bug fix in the pool element allocation

src/frontend/init/yaksa_init.c, src/frontend/iov/yaksa_iov.c
Bug-fix in detection of contiguous pairtypes.
=> Bug-fix in detection of contiguous pairtypes

src/frontend/pup/yaksa_iunpack.c
If the datatype to unpack is empty, return the correct "actual_unpack_bytes" value.
=> unpack: missed some corner cases in pmodels/yaksa#68

Makefile.am
Add README.md to the distributed file list
=> Add README.md to the distributed file list

maint/release.py
The intent is to make sure the script checks the todo list for us, instead of we doing it manually.
=> Created a release script

.gitignore, maint/gentests.py, src/frontend/flatten/yaksa_unflatten.c, test/dtpools/src/dtpools.c, test/dtpools/src/dtpools_internal.h, test/dtpools/src/dtpools_misc.c, test/flatten/Makefile.mk, test/flatten/flatten.c, test/iov/Makefile.mk, test/iov/iov.c, test/pack/Makefile.mk, test/pack/pack.c
Our testing of multithreaded execution was too simplistic.  This PR adds additional tests.  It also fixes a bug that showed up by adding these tests.
=> Add tests to stress multithreaded execution for yaksa

src/backend/cuda/pup/yaksuri_cudai_pup.c, src/backend/seq/pup/yaksuri_seq_pup.c
Squash -Wstack-usage= warnings
=> backend: warning squash

src/backend/cuda/hooks/yaksuri_cudai_info_hooks.c, src/backend/cuda/hooks/yaksuri_cudai_type_hooks.c, src/backend/seq/hooks/yaksuri_seq_hooks.c, src/util/yaksu_pool.c
coverity: fixes for issues reported by coverity
=> coverity: fixes for issues reported by coverity

.gitignore
update gitignore for newly added testlist files
=> .gitignore: update gitignore for newly added testlist files

m4/aclocal_cc.m4, maint/clmake, src/backend/cuda/pup/yaksuri_cudai_pup.c, src/backend/cuda/subconfigure.m4, src/backend/src/yaksur_pup.c
Warning squashes in the CUDA backend
=> cuda: warning squashes

src/frontend/types/yaksa_dup.c
type: remove structurally dead code
=> type: remove structurally dead code

src/frontend/include/yaksa.h.in, src/frontend/pup/yaksi_request.c, src/frontend/types/yaksa_free.c, src/frontend/types/yaksi_type.c
Some miscellaneous fixes to yaksa.
=> Miscellaneous fixes

.gitignore
.gitignore: add pycache to gitignore
=> .gitignore: add pycache to gitignore

src/frontend/include/yaksi.h, src/frontend/init/yaksa_init.c, src/frontend/pup/yaksi_request.c
=> valgrind: fix valgrind leaks

.gitignore, maint/gentests.py, src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/pup/yaksuri_cudai_get_ptr_attr.c, src/backend/cuda/pup/yaksuri_cudai_pup.c, src/backend/seq/include/yaksuri_seqi.h, src/backend/src/yaksur_pre.h, src/backend/src/yaksur_pup.c, src/backend/src/yaksuri.h, src/backend/src/yaksuri_progress.c, test/pack/Makefile.cuda.mk, test/pack/pack.c
Support managed memory buffers.
=> Allow for Managed Memory

src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/pup/yaksuri_cudai_pup.c, src/backend/src/yaksur_pre.h, src/backend/src/yaksuri_progress.c
=> Fix incorrect buffer checking

src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c, src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/pup/yaksuri_cudai_event.c, src/backend/src/yaksur_pre.h, src/backend/src/yaksuri_progress.c
=> Fixes to the Events API

src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
If CUDA is setup in exclusive compute mode and the user did not filter the devices using CUDA_VISIBLE_DEVICES, disable CUDA support in Yaksa.
=> backend/cuda: disable CUDA in exclusive mode

src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c, src/backend/cuda/hooks/yaksuri_cudai_info_hooks.c, src/backend/cuda/include/yaksuri_cudai.h, src/backend/cuda/pup/yaksuri_cudai_get_ptr_attr.c, src/backend/src/yaksur_hooks.c, src/backend/src/yaksur_pre.h, src/backend/src/yaksur_pup.c, src/backend/src/yaksuri.h, src/backend/src/yaksuri_progress.c, src/frontend/include/yaksi.h, src/frontend/info/yaksa_info.c, src/frontend/types/yaksa_subarray.c, test/pack/pack.c
Adds the necessary setup to pass info hints to Yaksa.  This PR includes a few info hints to pass the buffer attributes into Yaksa.
=> Info hints for buffer attributes

src/backend/src/yaksur_pup.c
Once the request is enqueued into the progress engine, the GPU driver
cannot be updated anymore.
=> backend: fix threading bug

src/backend/src/yaksur_hooks.c
Bug-fix: malloc/free functions were not skipping uninitialized drivers
=> Bug-fix: malloc/free functions were not skipping uninitialized drivers

test/dtpools/src/dtpools_desc.c
Simplify the DTPools description to make it more readable.  If the description is repeating many times, display only the first few elements.
=> Improve DTPools description

maint/gentests.py, test/simple/lbub.c
test/simple: add the lbub test
=> test/simple: add the lbub test

autogen.sh
Improve autogen error checking
=> Improve autogen error checking

src/backend/cuda/genpup.py, src/backend/seq/genpup.py
Attempt to generalize the assignment code inside pack/unpack to allow for cases where the displacement of buffers passed by users does not directly align to the basic type size.
=> Generalize assignment code

src/backend/cuda/subconfigure.m4, src/backend/ze/subconfigure.m4
backend: minor warning squashes
=> backend: minor warning squashes

src/frontend/include/yaksa.h.in
=> yaksa.h: documentation fixes

src/backend/src/yaksuri_progress.c
=> backend: support managed buffer that is associated to a single device

src/backend/cuda/include/yaksuri_cudai.h, src/backend/gencomm.py, src/backend/seq/include/yaksuri_seqi.h, src/backend/ze/include/yaksuri_zei.h
=> backend: save string name of kernel of each datatype for debugging

test/dtpools/src/dtpools_init_verify.c
dtpools: bug-fix in the initialization of data
=> dtpools: bug-fix in the initialization of data

maint/clmake, src/backend/ze/genpup.py, src/backend/ze/hooks/yaksuri_ze_init_hooks.c, src/backend/ze/hooks/yaksuri_zei_type_hooks.c, src/backend/ze/include/yaksuri_zei.h, src/backend/ze/md/yaksuri_zei_md.c, src/backend/ze/pup/Makefile.mk, src/backend/ze/pup/yaksuri_zei_pup.c, src/backend/ze/subconfigure.m4, test/pack/pack-ze.c
=> Fix warnings

maint/gentests.py
=> gentest.py: add tests with float

maint/gentests.py, src/backend/gencomm.py, src/backend/seq/genpup.py, src/backend/ze/genpup.py, test/pack/pack.c
This PR adds support for reduction operations (SUM, PROD, REPLACE) for complex types.
=> Add reduction support for complex datatypes

src/backend/ze/genpup.py, src/backend/ze/hooks/yaksuri_ze_init_hooks.c, src/backend/ze/include/yaksuri_zei.h, src/backend/ze/md/yaksuri_zei_md.c, src/backend/ze/pup/yaksuri_zei_get_ptr_attr.c, test/pack/pack-ze.c, test/pack/pack.c
=> ZE backend improvment

.gitignore
Looks like a generated file was added recently but the ignore didn't go with it.
=> Add gitignore for tests

src/backend/ze/hooks/yaksuri_ze_init_hooks.c, src/backend/ze/include/yaksuri_zei.h, src/backend/ze/pup/yaksuri_zei_pup.c
Implement the blocking API for ze backend
=> backend/ze: implement synchronize hook

src/backend/cuda/subconfigure.m4
Add a way to specify user flags for nvcc. Improve logging of compilation test.
=> config: Improvements to nvcc test

src/backend/cuda/subconfigure.m4
User asked if this could be added, which led me to learn about these settings https://en.wikipedia.org/wiki/CUDA#GPUs_supported.
Support latest CUDA compute capabilities.
=> cuda: Support new ampere compute

CHANGES
Highlight additions and changes since the 0.1x branch was made.
=> add CHANGES file

src/backend/src/yaksuri_progress.c
With the change to lazily init CUDA resources, a crash occurs in MPICH when doing certain device-to-device transfers. The underlying issue is when using a mapped device (supplied via info) for transfers, we need to use the mapped device in the p2p check. Otherwise peer access might not be initialized, resulting in illegal memory access.
Fix CUDA support in MPICH with yaksa lazy init.
=> backend: Use correct device for peer access check

src/backend/hip/genpup.py, src/backend/hip/hooks/yaksuri_hip_init_hooks.c, src/backend/hip/include/yaksuri_hipi.h, src/backend/hip/pup/yaksuri_hipi_event.c, src/backend/hip/pup/yaksuri_hipi_pup.c, src/backend/src/yaksur_pup.c, src/backend/src/yaksuri_progress.c, src/frontend/include/yaksi.h, src/frontend/pup/yaksi_request.c
Add HIP hooks for `pack_with_stream`, `unpack_with_stream`, and `launch_hostfn`. This completes the HIP support for yaksa API `yaksa_pack_stream` and `yaksa_unpack_stream`.
=> hip: add HIP backend support for stream APIs

src/backend/hip/subconfigure.m4
Adding option to let HIPCC auto-detect target id. Cleaned up option help strings.
Tested and confirmed fixing building problem on Crusher.
#222 would not be needed once this comes in.
=> hip: improve --with-hip-sm option 

COPYRIGHT
Signed-off-by: Simon Pickartz <pickartz@par-tec.com>
Update the external contributors.
=> copyright: add ParTec AG as a contributor

src/frontend/pup/yaksi_iunpack_backend.c
Need to apply the same fix to yaksi_iunpack_backend.
Ref: PR #238 
Signed-off-by: Hui Zhou <hzhou321@anl.gov>
=> frontend: work around for clang bug for unpack

src/backend/cuda/cudalt.sh, src/backend/hip/hiplt.sh
`libtool` may not exist in users system paths. Use the configure generated libtool script in stead.
=> backend: use ./libtool in cudalt.sh
