- configure.ac
Signed-off-by: Pavan Balaji <balaji@anl.gov>
In [9bc91a821367], the calculation `YAKSA_NUMVERSION` was protected, so it would only be calculated in a release version.  However, the remaining variables were still being always calculated.  This was throwing warnings in the direct git-based source build.
Fixes warnings.
> build: create NUMVERSION only for released copies

- src/backend/cuda/include/yaksuri_cuda.h
- src/backend/cuda/pup/Makefile.mk
- src/backend/cuda/pup/yaksuri_cuda_buftype.c
The buffer type checking function was defined as a static inside the device exposed header file.  This was causing it to be included in files that didn't use the function at all and was throwing warnings.  We could have silenced it with an attribute, but it is cleaner to simply move the function into a `.c` file.
Fixes warnings.
> Cleanup the buffer type checking function in the CUDA backend

- m4/aclocal_cc.m4
This compiler argument throws several warnings in genuine cases that are hard to fix.
Disable this check for now.
Fewer unnecessary warnings.
> build: remove -Wcast-qual checking

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
`cudaStreamCreate` creates a stream that implicitly synchronizes with the
default stream (stream 0). Thus, if work on the created stream is
interleaved with work on the default stream the two will be serialized.
This behavior can be fixed by replacing `cudaStreamCreate` with
`cudaStreamCreateWithFlags` and using the `cudaStreamNonBlocking` flag for
the new stream.
Fixes issue https://github.com/pmodels/yaksa/issues/31
> cuda: make stream fully asynchronous

- src/backend/cuda/hooks/Makefile.mk
- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/hooks/yaksuri_cudai_type_hooks.c
- src/backend/cuda/include/yaksuri_cuda_post.h
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/Makefile.mk
- src/backend/cuda/pup/yaksuri_cudai_event.c
- src/backend/cuda/pup/yaksuri_cudai_get_memory_type.c
- src/backend/cuda/stub/yaksuri_cuda_post.h
- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_pre.h
- src/backend/src/yaksur_pup.c
- src/backend/src/yaksur_request.c
- src/backend/src/yaksuri.h
- src/backend/src/yaksuri_progress.c
- src/frontend/include/yaksa.h.in
- src/frontend/init/yaksa_init.c
- test/pack/pack.c
The backend glue layer includes a large amount of GPU management code.  But most of this code is not specific to a GPU type.  This PR abstracts the GPU type from the code, so as to reduce the footprint of "cuda" in the code.  Specifically, the algorithm logic that is independent of CUDA does not directly reference any CUDA-specific content.
This PR is in preparation for supporting other GPU types (e.g., AMD and Intel GPUs).
> Abstract GPU related code

- test/flatten/flatten.c
- test/iov/iov.c
- test/pack/pack.c
dtpools no longer manages the description string. This is now generated
on demand by tests for single cases in which debugging info is needed.
The description string is thus handled by the test and should be freed
afterwards.
> test: free description string

- src/backend/cuda/Makefile.mk
- src/backend/cuda/subconfigure.m4
Allow the CUDA backend to build executables for multiple architectures, including all supported architectures depending on the CUDA version.  Users still have the option to specialize builds for specific architectures, but are not required to do so.
Adds convenience for the user so they do not have to figure out the exact GPU architecture they are building for.  Also helps binary distributors where the binary code needs to work on multiple architectures.
On the negative side, this significantly increases the build time.  In my experiments, the default (parallel) build goes up from 35 seconds to 315 seconds.
> CUDA fat binaries

- autogen.sh
- src/backend/cuda/genpup.py
- src/backend/seq/genpup.py
Allow for users to generate different levels of nesting, thus trading off performance with the library size and build time.  The default is set to 3 levels of nesting, as before.
> Allow users to control the maximum number of nesting levels generated for the pup functions

- src/backend/cuda/genpup.py
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/util/yaksu_base.h
This PR allows us to have as many thread blocks as allowed in all of the three dimensions of the block grid combined.
This would allow us to pack/unpack larger data sizes than before.
> CUDA: Allow for more thread blocks than the X dimension of the block grid

- src/frontend/pup/yaksa_ipack.c
- src/frontend/pup/yaksa_iunpack.c
This is useful when the caller of yaksa is a library itself and does not know what kind of datatype got passed down to it.
> Allow users to pass zero-byte datatypes to pack/unpack

- examples/contig.c
- examples/fuf.c
- examples/hindexed.c
- examples/hindexed_block.c
- examples/hvector.c
- examples/indexed.c
- examples/indexed_block.c
- examples/iov.c
- examples/resized.c
- examples/subarray.c
- examples/vector.c
- src/frontend/include/yaksa.h.in
- src/frontend/init/yaksa_init.c
- test/flatten/flatten.c
- test/iov/iov.c
- test/pack/pack.c
- test/simple/simple_test.c
- test/simple/threaded_test.c
Allow for attributes to be passed to yaksa during initialization.  Though we do not have any attributes right now, this will help future-proof the API somewhat.
> Add init attributes to yaksa_init

- src/frontend/flatten/yaksa_unflatten.c
When we flatten a datatype, we include the refcount for that type.
However, when we unflatten, we are essentially creating a new type.
So we need to reset the refcount back to 1.
> unflatten: reset refcount for newly unflattened types

- src/frontend/init/yaksa_init.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
Look at the count, the blocklengths and the sizes of each of the child
types to decide whether a new type is a zero-byte type.
> Better detect zero-byte types

- src/backend/cuda/genpup.py
- src/backend/seq/genpup.py
- src/frontend/include/yaksi.h
- src/frontend/init/yaksa_init.c
These are contiguous, but cannot necessarily be represented as a
single C type.  They'd need to be represented by two C types in most
cases.
> Treat Fortran complex types as pairtypes

- src/frontend/iov/yaksa_iov.c
- test/iov/iov.c
For pack/unpack, we always respected the basic type boundaries, so we never packed partial basic types.  But we were not doing the same for IOVs.
> Always pack full elements, never partial

- configure.ac
When we are embedded in mpich, the debugging option might get passed
in as --enable-g instead of --enable-debug.
> Add --enable-g as an alias for --enable-debug

- examples/contig.c
- examples/fuf.c
- examples/hindexed.c
- examples/hindexed_block.c
- examples/hvector.c
- examples/indexed.c
- examples/indexed_block.c
- examples/resized.c
- examples/subarray.c
- examples/vector.c
- src/frontend/include/yaksa.h.in
- src/frontend/include/yaksi.h
- src/frontend/pup/yaksa_iunpack.c
- src/frontend/pup/yaksi_iunpack.c
- src/frontend/pup/yaksi_iunpack_element.c
- test/flatten/flatten.c
- test/pack/pack.c
- test/simple/simple_test.c
- test/simple/threaded_test.c
When the user receives data in a pipelined fashion, it is possible
that the number of bytes received might not be able to fully fit a
basic datatype element.  In such cases, yaksa needs to tell the user
how much data was actually unpacked, so the user can keep track of the
remaining bytes.
Fixes pmodels/yaksa#67
> Unpack: return the actual number of unpacked bytes

- configure.ac
In embedded builds, the user might provide extra options to `--enable-fast`.  Ignore them.
> build: ignore unrecognized options to --enable-fast

- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_struct.c
Flattening/unflattening of datatypes can be expensive when there are many child datatypes involved.  This is particularly true for structs, where the number of child datatypes can be arbitrarily large.  This PR optimizes flattening/unflattening in some cases.
> Optimizations for flattening of datatypes

- Makefile.am
- src/frontend/include/Makefile.mk
This is needed on systems where installing the library disables embedding the library.  See pmodels/mpich#4496.
> build: avoid installing yaksa for embedded builds

- src/backend/cuda/hooks/yaksuri_cudai_info_hooks.c
- src/backend/cuda/include/yaksuri_cuda_pre.h
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/backend/seq/hooks/yaksuri_seq_hooks.c
- src/backend/seq/include/yaksuri_seq_pre.h
- src/backend/seq/include/yaksuri_seqi.h
- src/backend/seq/pup/yaksuri_seq_pup.c
- src/frontend/include/yaksi.h
- src/frontend/iov/yaksa_iov.c
This PR allows pack/unpack to use kernel-based or IOV-based packing/unpacking depending on datatype density.  It also allows users to tune the threshold for the switchover using info arguments.
This is more important for GPU-based pack/unpack, where IOV-based packing can be done entirely with GPU memcpy operations instead of launching a kernel.
> Allow pack/unpack to switch to iov-based packing

- configure.ac
- m4/aclocal_cc.m4
- maint/clmake
- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_pup.c
- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/init/yaksa_init.c
- src/frontend/iov/yaksa_iov.c
- src/frontend/pup/yaksi_request.c
- src/frontend/types/yaksi_type.c
- src/util/yaksu_pool.c
- src/util/yaksu_pool.h
The previous warning tests in yaksa were basically bogus.  The strict option was missing the optimization flag (which disabled some warnings), and the setting of the compiler to `gcc-4` and `gcc-9` was completely bogus (it was never getting set in the jenkins script).  Plus, there was no testing with other compilers.  This PR was done in conjunction with improving the jenkins test for better warning checking.
> Several warning squashes

- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_dup.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_vector.c
In some cases, the user passes a more complex type, which can be
converted to a simpler type.  Try to convert each type to the simplest
form that it can take.  This increases the probability that it would
be better optimized by the backend.
> types: add special cases for type creation

- src/frontend/init/yaksa_init.c
Use yaksa_type_free so that hooks are executed. Fixes memory leaka
found with AddressSanitizer. See #89.
Fix memory leaks.
> init: free builtin types properly in finalize

- src/frontend/init/yaksa_init.c
- src/util/yaksu_pool.c
Fix remaining leaks found with AddressSanitizer. One in initialization, and one in the pool allocator.
Fix memory leaks.
> Fix memory leaks in init and pool allocator

- maint/gentests.py
> gentest.py: fix struct type string - using '+' instead of ','

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/hooks/yaksuri_cudai_type_hooks.c
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/backend/src/yaksuri_progress.c
- src/frontend/pup/yaksa_ipack.c
- src/frontend/pup/yaksa_iunpack.c
- src/frontend/pup/yaksi_ipack.c
- src/frontend/pup/yaksi_ipack_element.c
- src/frontend/pup/yaksi_iunpack.c
- src/frontend/pup/yaksi_iunpack_element.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
As per the C++ standard:
```
It is possible to transfer into a block, but not in a way that
bypasses declarations with initialization. A program that jumps from a
point where a local variable with automatic storage duration is not in
scope to a point where it is in scope is ill-formed unless the
variable has POD type (3.9) and is declared without an initializer
```
I haven't searched for it in the C99 standard, but the concerns are
valid even for C99 and compilers such as PGI seem to throw warnings
for it even with C99 code.  Separating out the declaration statement
from the initialization statement should workaround these warnings.
Signed-off-by: Pavan Balaji <balaji@anl.gov>
Warning free builds with the PGI compiler.
> warnings: avoid inline initialization of POD variables

- maint/gentests.py
- maint/yutils.py
- src/backend/cuda/genpup.py
- src/backend/gencomm.py
- src/backend/seq/genpup.py
Some platforms still default "python" to python2.  Uniformly require
python3 in all scripts so we only depend on python3, rather than a
combination of python2 and python3.
> scripts: uniformly require python3

- src/backend/cuda/genpup.py
- src/backend/seq/genpup.py
- src/frontend/include/yaksa.h.in
- src/frontend/init/yaksa_init.c
- test/dtpools/src/dtpools_init_verify.c
- test/dtpools/src/dtpools_misc.c
We create a number of user-visible handles, one for each c99 datatype,
but they all internally map to a smaller set of objects.
> types: include all C99 primitive types

- examples/contig.c
- examples/fuf.c
- examples/hindexed.c
- examples/hindexed_block.c
- examples/hvector.c
- examples/indexed.c
- examples/indexed_block.c
- examples/iov.c
- examples/resized.c
- examples/subarray.c
- examples/vector.c
- src/frontend/include/yaksa.h.in
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_dup.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
- test/dtpools/src/dtpools_attr.c
- test/dtpools/src/dtpools_misc.c
- test/simple/simple_test.c
- test/simple/threaded_test.c
Adding info hints to type creation routines as requested by the UCX datatypes working group folks.
These hints are unused at this point, but adding them in for future use.
> types: update type creation functions to take an info hint

- test/dtpools/src/dtpools_attr.c
We calculate the potential extent of a datatype, make sure it fits inside yaksa's extent type format, and then decide whether we can use this datatype or not.  For this, we need the internal calculation of the extent to always be done with 64 bits, so we can eventually check if it is within the required range or not.
> Fixes for 32-bit systems

- test/dtpools/src/dtpools_attr.c
> dtpools: warning squash

- src/frontend/pup/yaksi_iunpack.c
Cleans up a warning for an unused variable when `assert` goes away.
> Suppress unused variable warning

- src/frontend/include/yaksa.h.in
The embedded documentation in `yaksa.h.in` had typos mistaking the `lb` parameter as `[in]` when they should be `[out]`.
> comment: fix typos in yaksa.h.in

- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/include/yaksa.h.in
- src/frontend/include/yaksi.h
- src/frontend/init/yaksa_init.c
- src/frontend/pup/yaksi_request.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_dup.c
- src/frontend/types/yaksa_free.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
- src/frontend/types/yaksi_type.c
- src/util/yaksu_handle_pool.c
- src/util/yaksu_handle_pool.h
Generalize handle management, and create a handle cache, for faster conversion of handles to internal objects.
> Lockfree conversion of handle to internal object

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/include/yaksuri_cuda_post.h
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/yaksuri_cudai_event.c
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/backend/cuda/stub/yaksuri_cuda_post.h
- src/backend/seq/include/yaksuri_seq_post.h
- src/backend/seq/pup/yaksuri_seq_pup.c
- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_pre.h
- src/backend/src/yaksur_pup.c
- src/backend/src/yaksur_request.c
- src/backend/src/yaksuri.h
- src/backend/src/yaksuri_progress.c
- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/include/yaksa.h.in
- src/frontend/include/yaksi.h
- src/frontend/init/yaksa_init.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_dup.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_vector.c
- src/frontend/types/yaksi_type.c
- src/util/yaksu_buffer_pool.c
- src/util/yaksu_buffer_pool.h
This PR revamps the Yaksa progress engine to convert it to a cleaner state machine.  The event and buffer management are now completely hoisted up to the glue layer (the GPU drivers do not need to know anything about temporary buffers).  Different buffer types are managed as separate smaller functions to avoid code clutter.
> Revamped progress engine

- src/backend/cuda/subconfigure.m4
CUDA 11 dropped `compute_30` support http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/), but by default (without explicitly setting `--with-cuda-sm`), Yaksa tries to compile `compute_30`, which causes a compilation error. This patch fixes it by excluding `compute_30` when CUDA 11 is used.
For example, `compute_30` is not in allowed values.
```sh
$ nvcc --help
...
--gpu-architecture <arch>                       (-arch)
...
Note: the values compute_30, compute_32, compute_35, compute_37, compute_50,
sm_30, sm_32, sm_35, sm_37 and sm_50 are deprecated and may be removed in
a future release.
Allowed values for this option:  'compute_35','compute_37','compute_50',
'compute_52','compute_53','compute_60','compute_61','compute_62','compute_70', …
```
> cuda: exclude compute_30 when CUDA 11 is used

- autogen.sh
This allows CI jobs to easily control nested pup levels. The direct
autogen argument can't be used without changing the default for embedded
builds such as mpich.
> autogen: add check for YAKSA_AUTOGEN_PUP_NESTING

- src/backend/cuda/subconfigure.m4
libcudart requires libstdc++, but it does not seem to have an explicit dependency on it.  Try to add it in the build, if it is available.
> backend/cuda: add libstdc++ dependency for CUDA

- src/util/yaksu_atomics.h
Solaris compilers complain:
"src/util/yaksu_atomics.h", line 35: void function cannot return value
Remove "return" so that the compiler knows nothing is returned to the caller.
Fix build on Solaris with suncc compiler.
> atomics: Remove return from void function

- test/pack/pack.c
Fix a leak when freeing the temporary buffer in pack test. Found with AddressSanitizer.
Fix memory leak.
> test/pack: Fix memory leak

- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/frontend/iov/yaksa_iov.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
Detection of contig types in Yaksa was somewhat broken.  This was compounded by bugs in the IOV code.  This PR fixes both.
Fixes https://github.com/pmodels/yaksa/issues/109.
> Fixes to contig detection

- configure.ac
Allow for ndebug to be passed as an option, and ignore options that we
do not recognize.  This allows yaksa to be used in embedded mode,
where we might not recognize all options passed to us.
> build: improve --enable-fast configure option

- src/frontend/init/yaksa_init.c
Freeing built-in types may require accessing backend devices, it needs to
be called before devices are freed in the finalize_hook.
> frontend: free built-in types before calling finalize_hook

- test/runtests.py
Always print failure in the summary file even though there is no error output.
Also add a "make testing-pack" to run test "pack" only
> test: fix runtest script to always print failure in the summary

- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/gencomm.py
- src/backend/seq/include/yaksuri_seqi.h
Each backend defines YAKSURI_KERNEL_NULL to be the right value for
uninitialized kernels.
> backend: use YAKSURI_KERNEL_NULL for uninitialized kernels

- src/backend/src/yaksur_hooks.c
Solaris compilers are really picky about returning from void
functions. Separate the free function call from the return statement
to make the compiler happy.
> backend: Fix Solaris build error

- src/backend/src/yaksur_pup.c
Use UNSET for the case where the GPU driver ID is not queried yet.
LAST is used when the query is done, but no GPU driver claimed the
buffers.
Without this, we were always repeating the query for each subreq, when
no GPU driver claimed the buffers.
> backend/glue: distinguish UNSET vs. LAST GPU driver ID

- src/backend/src/yaksur_pup.c
backend/glue: skip over buffer attr query if already done
> backend/glue: skip over buffer attr query if already done

- src/frontend/pup/yaksi_iunpack_element.c
If a partial pack returned without packing the entire block, it means
that we have hit a type boundary.  In that case, simply return.
> frontend/unpack: bug-fix for unpack_element

- src/backend/ze/pup/Makefile.mk
> backend/ze: fix use of wrong SPIRV file name for inline generation

- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- src/backend/ze/hooks/yaksuri_zei_type_hooks.c
- src/backend/ze/include/yaksuri_zei.h
- src/backend/ze/md/yaksuri_zei_md.c
- src/backend/ze/pup/yaksuri_zei_event.c
- src/backend/ze/pup/yaksuri_zei_pup.c
Switched from indirect-access mode to finer-grained control of buffer
residency to avoid race condition in handling managed buffers.
Improved locking on events and kernel invocation.
> backend/ze: fixes for multi-threading

- src/backend/ze/pup/yaksuri_zei_get_ptr_attr.c
- test/pack/pack-ze.c
Latest L0 requires the property descriptor to be set zero
> backend/ze: set memory property descriptor to zero

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/backend/src/yaksur_pre.h
- src/backend/src/yaksuri_progress.c
- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- src/backend/ze/include/yaksuri_zei.h
- src/backend/ze/pup/yaksuri_zei_pup.c
While CUDA does not need this functionality, Ze can take advantage of
it to chain a bunch of kernels and then issue them all during the
flush operation.
> backend: added a new flush_all function to flush kernels

- src/backend/src/yaksur_hooks.c
- src/frontend/info/yaksa_info.c
- test/pack/pack-common.c
- test/pack/pack-common.h
- test/pack/pack-cuda.c
- test/pack/pack-ze.c
- test/pack/pack.c
The purpose of this PR is add a way to tell yaksa the both `in_buf` and `out_buf` is cpu host memory. This is useful when yaksa is configured with GPU support but the application doesn't use gpu memory or the application knows when their buffer is entirely from CPU and thus doesn't need to pay the pointer attribute query overhead.
Fixes #168
> infohint: add nogpu as a gpudriver_id hint

- examples/fuf.c
- examples/hindexed.c
- examples/indexed.c
- examples/indexed_block.c
- examples/iov.c
- examples/subarray.c
- src/backend/cuda/genpup.py
- src/backend/cuda/include/yaksuri_cudai_base.h
- src/backend/cuda/md/yaksuri_cudai_md.c
- src/backend/seq/genpup.py
- src/backend/ze/genpup.py
- src/backend/ze/include/yaksuri_zei_md.h
- src/backend/ze/md/yaksuri_zei_md.c
- src/frontend/flatten/yaksa_flatten.c
- src/frontend/flatten/yaksa_flatten_size.c
- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/include/yaksa.h.in
- src/frontend/include/yaksi.h
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
- test/dtpools/src/dtpools_attr.c
- test/dtpools/src/dtpools_init_verify.c
- test/dtpools/src/dtpools_internal.h
- test/dtpools/src/dtpools_misc.c
Modify all yaksa type creation function, e.g.  `yaksa_type_create_contig_x`, `yaksa_type_create_vector_x`, etc. to use `intptr_t` typed arguments in stead of `int`. This really only affects:
* `yaksa_type_create_indexed_block`
* `yaksa_type_create_indexed`
* `yaksa_type_create_hindexed`
* `yaksa_type_create_struct`
* `yaksa_type_create_subarray`
, because they now use `intptr_t` arrays rather than `int` array. For all scalar parameters, it should be automatically converted to the larger integer type gracefully by the compiler.
> type: change the type creation API to use intptr_t

- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_post.h
- src/frontend/init/yaksa_init.c
Yaksa will query gpu devices during init. This query can have huge
latency especially when multiple processes are trying to query the device at
the same time. With CUDA, cudaGetDeviceCount and checking peer access
are the most suceptible operations.
This commit allows "nogpu" infohint to skip the gpu driver setup.
Skipping gpu driver setup leaves yaksuri_global.gpudriver[id].hooks
NULL, thus will skip driver finalize. If somehow there is access to gpu
driver during runtime, I guess it will simply segfault (due to NULL
hooks).
TODO: a better solution may be to allow lazy gpu initialization. This
can be helpful especially when not all process on the same node need
access GPU.
> init: skip gpu initialization with infohint

- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_pre.h
In order to pass info hint to yaksa_init, it is necessary to create info
before yaksa_init. But some facility, such as gpu driver hooks are not
inplace yet before init. This patch adds a pre_init flag to guard
against such inconsistencies. Currently, this simply prevents gpu driver
hooks to ever executed for such pre_init infos.
> info: fix info usage before yaksa_init

- m4/aclocal_libs.m4
- src/backend/cuda/subconfigure.m4
- src/backend/ze/subconfigure.m4
The previous macros will set "no" to the library path if `--without-cuda` is passed in. This PR makes it to work.
> config: allow --without-cuda to bypass cuda

- src/backend/src/yaksuri_progress.c
The current pack/unpack protocol switch code in `yaksuri_progress_enqueue` is complex and not easy to read. This patch refactors the long if-else based switch logic. The basic approach is to separate each situation (e.g., d2d_pack, d2rh_pack...) into subroutines so that later developers can easily find the place to optimize.
> backend/cuda: refactoring complex pack/unpack protocol switch in progress enqueue and minor bug fix

- src/backend/cuda/cudalt.sh
Use shift instead of array slicing syntax. Fixes a build issue on
systems with dash as /bin/sh, e.g. Ubuntu. Closes #180.
Fix build issue on Ubuntu.
> backend/cuda: Fix bashism in shell script

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/src/yaksur_pre.h
- src/backend/src/yaksuri_progress.c
- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
This PR contains two major changes:
1.  Add p2p-enabled case for the fast-path of **REPLACE** operation
2. [c346933b](https://github.com/pmodels/yaksa/commit/c346933b5262809b433c322a2552dd1c06f2e683) missed the fast-path check for non-REPLACE reduce operations. Now we add it back. Below are the fast-path conditions for **non-REPLACE** operations:
- d2d pack/unpack: same device and buffer is aligned
- d2m or m2d pack/unpack: same device or device-host, and with aligned buffer
> backend: fix fast-path conditions for reduce operations

- maint/gentests.py
- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/pup/yaksuri_cudai_pup.c
- src/backend/src/yaksur_pre.h
- src/backend/src/yaksuri_progress.c
- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- src/frontend/include/yaksa.h.in
- src/frontend/include/yaksi.h
- src/frontend/init/yaksa_init.c
- src/frontend/pup/Makefile.mk
- src/frontend/pup/yaksa_ipack.c
- src/frontend/pup/yaksa_iunpack.c
- src/frontend/pup/yaksa_pack.c
- src/frontend/pup/yaksa_unpack.c
- src/frontend/pup/yaksi_request.c
- test/pack/Makefile.mk
- test/pack/pack.c
Current API supports only nonblocking `ipack|iunpack` and `request_wait`. The user can use them to implement blocking pack|unpack, however, it causes suboptimal performance in fast-path copy. Performance study with CUDA showed that use of **event-creation-record-destroy** APIs in the current nonblocking approach introduce about **3us~** consistent overhead. Such an overhead is significant at the fast-path of d<->d, d<->m, d<->rh copy which usually takes latency only at 8~15us.
On the user side (e.g., in MPICH), yaksa APIs are often used in a blocking manner depends on the communication protocol or latency/message-rate preference. Thus, using the underlying nonblocking yaksa routines introduce unnecessary overhead. 
This PR implements the blocking `pack|unpack` API. Thus, yaksa can …
> frontend/backend: implement blocking pack/unpack and optimize fast-path

- autogen.sh
- maint/gentests.py
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_struct.c
- test/simple/Makefile.mk
- test/simple/test_contig.c
The previous code is incorrect in only checking for starting position
between each block in yaksi_type_create_hindexed. We need check whether
previous upper bound is the same as the current lower bound.
Reference: https://github.com/pmodels/mpich/issues/5391
TODO:
> type_create: fix checking for contig

- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksur_post.h
- src/backend/src/yaksur_pre.h
- src/frontend/init/yaksa_init.c
Backport of gpu initialization skip feature.
Add more control over GPU initialization to MPICH 3.4.x series.
> init: skip gpu initialization with info hint [0.1x]

- src/backend/src/yaksur_hooks.c
[previous backport missed the actual nogpu info hint addition]
Add a way for application to tell yaksa that both in_buf and out_buf are
host memory.
Signed-off-by: Hui Zhou <hzhou321@anl.gov>
> infohint: add nogpu as a gpudriver_id hint [0.1x]

- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- src/backend/ze/include/yaksuri_zei.h
- src/backend/ze/pup/yaksuri_zei_get_ptr_attr.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
- test/pack/pack-common.c
- test/pack/pack-common.h
- test/pack/pack-cuda.c
- test/pack/pack-ze.c
- test/pack/pack.c
a collection of fixes for Intel GPU backend:
1. error checking for yaksur_type_create_hook
2. fix device id for subdevices
3. improve pack test by reusing command lists
> ze: misc fixes

- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksuri.h
- src/backend/src/yaksuri_progress.c
For device-to-device operations, the mapped_device hint can be used to
influence which device context (stream) to use.
If the buffer is mapped with ipc, using the stream of mapped_device has
better performance. And in the case of launching kernel, it has to be
launched on the mapped device.
> info: add info hint mapped_device

- src/backend/cuda/subconfigure.m4
The CC may include options, a typical example is `gcc -std=gnu99`. This
won't work with nvcc -ccbin option, which expects a filepath. Strip the
option. The kernel code used in yaksa works without gnu99 option.
This fixes embedded build in MPICH
> config: fix checking of nvcc

- configure.ac
MPICH uses option --enable-fast=all to enable most common fast options.
However, yaksa ignores it, resulting from worse performance than the default
-O2. Add the option to avoid surprises when building mpich.
Once merged, this should fix the current mpich nightly enable fast test (TIMEOUT in `./rma/large_acc_flush_local`).
> config: add --enable-fast=all

- src/backend/src/yaksuri_progress.c
- src/backend/ze/pup/yaksuri_zei_event.c
In case of REPLACE operation and contiguous datatype, remove the unnecessary device bounce buffer used for packing or unpacking (which is only needed if it is non-contiguous type). This saves one extra copying for performance.
This PR optimizes for copy between device and unregistered host buffer, and between device to device (w/o p2p).
The third commit fixed a (long standing) bug in backend progress when a packing/unpacking of more than 16MB buffer may exit prematurely (i.e. when the device buffer pool runs out). We have seen validation errors on very large message in various OSU benchmarks due to this bug.
The fourth commit fixed a bug in ze for event_record.
> Optimize backend for contiguous datatype

- configure.ac
- src/backend/ze/subconfigure.m4
- src/frontend/bounds/yaksa_bounds.c
- src/frontend/flatten/yaksa_flatten.c
- src/frontend/flatten/yaksa_flatten_size.c
- src/frontend/flatten/yaksa_unflatten.c
- src/frontend/include/yaksi.h
- src/frontend/info/yaksa_info.c
- src/frontend/init/yaksa_init.c
- src/frontend/iov/yaksa_iov.c
- src/frontend/iov/yaksa_iov_len.c
- src/frontend/pup/yaksa_ipack.c
- src/frontend/pup/yaksa_iunpack.c
- src/frontend/pup/yaksa_pack.c
- src/frontend/pup/yaksa_pack_stream.c
- src/frontend/pup/yaksa_request.c
- src/frontend/pup/yaksa_unpack.c
- src/frontend/pup/yaksa_unpack_stream.c
- src/frontend/types/yaksa_blkindx.c
- src/frontend/types/yaksa_contig.c
- src/frontend/types/yaksa_dup.c
- src/frontend/types/yaksa_free.c
- src/frontend/types/yaksa_indexed.c
- src/frontend/types/yaksa_resized.c
- src/frontend/types/yaksa_struct.c
- src/frontend/types/yaksa_subarray.c
- src/frontend/types/yaksa_vector.c
Allow --enable-visibility to be used with configure
With -fvisibility=hidden, the entries of dynamic symbol table reduced from 17137 to 35:
```
nm -D ./libyaksa.so |  grep " T " | wc -l
35
```
Hopefully this improves the library loading.
It also reduced the binary by 2.3MB, which however is still huge at 864MB (with ze enabled).
> frontend: enable use of -fvisibility

- Makefile.am
We should not install `yaksa.pc` in embedded mode.
When merged, will fix https://github.com/hzhou/yaksa/pull/new/2109_no_pc
> build: do not install yaksa.pc in embedded mode

- configure.ac
- src/util/yaksu_buffer_pool.c
Only warn if handles are leaked in debug mode. MPICH users have noticed
yaksa warnings in default builds, which traditionally have not warned on
leaked MPI handles. This aligns the behavior between the two packages.
Silence leak warnings in default builds.
> util: Do not warn on leaked handles by default

- src/backend/cuda/subconfigure.m4
Apply same fix we did for building with PGI compilers, since they are the same as nvc/nvc++.
Fix CUDA-aware builds with nvc/nvc++.
> Fix build with Nvidia HPC compilers

- src/backend/ze/hooks/yaksuri_zei_type_hooks.c
- src/backend/ze/pup/yaksuri_zei_event.c
- src/backend/ze/pup/yaksuri_zei_pup.c
Fixes a few unused label warnings
> backend/ze: fix warnings about unused labels

- src/backend/cuda/subconfigure.m4
cuda: Allow configure to continue after nvcc check
If CUDA was not explicitly requested, it is possible that configure will
find the CUDA runtime library, then throw an error when it fails to find
nvcc. Remove AC_MSG_ERROR from the nvcc check, and instead let the
have_cuda/with_cuda variables determine if configure should continue
without CUDA support or throw an error. This fixes a build issue in the
Spack Gitlab CI environment.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
Fix default builds where CUDA libraries are available but `nvcc` is not in PATH.
> cuda: Allow configure to continue after nvcc check

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/include/yaksuri_cudai.h
- src/backend/cuda/include/yaksuri_cudai_base.h
- src/backend/cuda/pup/yaksuri_cudai_event.c
- src/backend/cuda/pup/yaksuri_cudai_pup.c
Some applications may seutp GPU affinity after MPI initialization. Delay
CUDA stream creation during yaksa init to avoid allocating resources on
GPUs a process may never use. See #212.
Signed-off-by: Ken Raffenetti <raffenet@mcs.anl.gov>
Avoid allocating resources on devices that will not be used.
> cuda: Delay stream creation

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/cuda/include/yaksuri_cudai_base.h
Calling cudaDeviceEnablePeerAccess may have the side effects of marking
off resource. Delay that to when we acutally need it.
> cuda: delay query p2p accessibility

- src/backend/ze/pup/Makefile.mk
- src/backend/ze/subconfigure.m4
For native compilation of Intel GPU kernels, a revision id may be needed for the ocloc compiler.
> backend/ze: add --ze-revision-id option to add rev id to ocloc compiler

- src/backend/cuda/genpup.py
- src/backend/gencomm.py
- src/backend/hip/genpup.py
- src/backend/seq/genpup.py
- src/backend/ze/genpup.py
Current codes fail to build when `--pup-max-nesting` is set to less than 2 due to incorrect/inconsistent behavior in genpup code:
1. `gencomm.populate_pupfns` always generates as max nesting level == 2
2. `genpup.py` always generates two-level-nesting kernels
3. `Makefile.pup.mk` always generates with targets of two-level-nesting kernels
4. `yaksuri_*i_pup.h` is generated correctly
Generating code with max nesting level < 2 and building will results in
1. compilation error in pupfns code because the missing decls for two-level-nesting kernels in `yaksuri_*i_pup.h`
2. wasted compilation for two-level-nesting kernels that should never be used.
This PR fixes this by adding necessary checks to the code generation.
> genpup: fix code generation for pup_max_nesting < 2

- src/backend/ze/pup/Makefile.mk
- src/backend/ze/pup/inline.py
- src/backend/ze/subconfigure.m4
This change allows yaksa to build one copy of kernel native binaries to include multiple devices.
For example, one kernel binary contains binary for both ATS and PVC.
> backend/ze: support compiling multiple devices with --ze-native

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksuri.h
Allocating registered buffers may be blocked by a gpu wait kernel. Since
CUDA is able to directly work with unregistered buffers, add an options
to use unregistered buffers for staging buffers.
> cuda: disable registered host buffer pool

- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
initialize ze_device_properties_t before calling zeDeviceGetProperties.
> backend/ze: initialize ze_device_properties_t before using it

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
- src/backend/src/yaksur_hooks.c
- src/backend/src/yaksuri.h
- src/backend/src/yaksuri_progress.c
When a wait kernel is running, the CUDA stream creation will get blocked and resulting in deadlocks. Initialize them during init to avoid such issue.
> cuda: no lazy stream creation with has_wait_kernel hint

- src/frontend/include/yaksa.h.in
- src/frontend/iov/Makefile.mk
- src/frontend/iov/yaksa_iov_len_max.c
Add new API yaksa_iov_len_max. This function return number of contiguous
segments within a maximum number of bytes. The API is useful for retrieving
partial iovs at a given byte offset.
Without this API, users may have to query the entire iov array. Not only
it can be very slow, the entire iov array may not fit in memory.
> iov: add yaksa_iov_len_max

- src/backend/ze/subconfigure.m4
set ze-native to "no" instead of empty string
> backend/ze: fix checking ze-native option

- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- src/backend/ze/include/yaksuri_zei.h
- src/backend/ze/pup/yaksuri_zei_event.c
- src/backend/ze/pup/yaksuri_zei_pup.c
Append task consecutively to an immediate cmd list without having to
wait for the previous tasks to finish
> backend/ze: simplify the use of immediate command list

- src/backend/src/yaksur_pup.c
- src/backend/src/yaksuri.h
- src/backend/src/yaksuri_progress.c
- src/frontend/include/yaksi.h
- src/frontend/pup/yaksi_ipack_backend.c
- src/frontend/pup/yaksi_iunpack_backend.c
- src/frontend/pup/yaksi_request.c
Currently, yaksa assumes all memory regions of derived datatypes to have the same memory type. However, in cases with absolute addressing, this is not necessarily true and therefore the caching of the memory type should be disabled. These patches avoid the caching of memory type information in such cases. Additionally, to support different memory types when subrequests are used, the `gpudriver_id` is stored on this level.
See also: https://github.com/pmodels/mpich/pull/6226
In case of absolute addressing, these patches will result in an increased amount of memory type queries.
> Support mixed memory types

- src/frontend/pup/yaksi_ipack_backend.c
In this recursive call, clang, verified in v10 and v11 with at least -O2, will use an outdated value of inbuf for branch switching but passing the correct inbuf value to actual function calls. Add an internal function to work around this bug. This bug was triggered by commit 2f5443c.
It currently shows up as failure on osx with many tests that uses a struct datatype with buffer=MPI_BOTTOM. For example:
```
not ok 1558 - ./datatype/struct_pack_mpi_bottom 1
---
Directory: ./datatype
File: struct_pack_mpi_bottom
Num-procs: 1
Timeout: 180
Date: "Sat Nov 19 01:42:45 2022"
...
```
> frontend: work around for a clang bug

- src/backend/ze/hooks/yaksuri_ze_init_hooks.c
- test/pack/pack-ze.c
Signed-off-by: Luzynski, Sebastian Jozef <sebastian.jozef.luzynski@intel.com>
Make code LevelZero spec compliant by setting `pNext` field to `NULL`
This fixes #236 . `pNext` field is required to be set by LevelZero specification. 
None, this change yields no functional changes. This makes code compliant with spec.
> backend: Populate pNext field in LevelZero structs

- src/backend/cuda/subconfigure.m4
We cannot use icc as the host compiler since it conflicts with recent CUDA versions. Therefore, we rely on the default GCC as it is binary compatible with icc.
This is done by simply omitting to set the `-ccbin icc`.  The test in `subconfigure.m4` can also be successfully passed by adding a `-std=c++11`.  However, this still prevents yaksa from being build by using icc as the host compiler.
CUDA code will be compiled by using GCC as the host compiler if icc is used within the build.
> cuda: allow user to set NVCC explicitly

- src/backend/cuda/Makefile.mk
- src/backend/cuda/subconfigure.m4
An extra check that resets NVCC.
Remove NVCC_FLAGS from makefile since it is already in the NVCC variable.
Also, move AC_SUBST to the outside as it does not depend on the branch.
Ref: https://github.com/pmodels/mpich/issues/6447
> config/cuda: do not reset NVCC

- src/backend/ze/pup/Makefile.mk
new ocloc adds .bin suffix even though -output_no_suffix is used.
> backend/ze: supports new version of ocloc

- src/backend/cuda/subconfigure.m4
PR1 simply add options for newer CUDA devices
PR2 add the auto detection. For CUDA 11.5+, we just use the new `-arch=native` option. For older version, we need to run a program to query the device version.
`--with-cuda-sm=auto` is set as the new default. The behavior is also changed to the follow:
1. If `auto` is set, any else options are ignored. e.g. `--with-cuda-sm=70,auto,80 == --with-cuda-sm=auto`.
2. Auto detection will fail only when CUDA version < 11.5 and no GPU present in the building node. If auto detection is failed, ~~we does not revert back to `--with-cuda-sm=all`~~. Probably should revert back to build all and throw out a warning.
3. Other options kept the existing behavior
> Adding auto CUDA compute capability detection

- CHANGES
There have been a good number of changes since 0.2. Since Spack defaults to using an external yaksa release to build MPICH, tagging 0.3 is a good idea so users can get the latest functionality.
> Update CHANGES in preparation of 0.3 release

- src/util/yaksu_handle_pool.c
The warning from the addressed location was still enabled for the non-debug build. This PR fixes it by adding ` ifdef YAKSA_DEBUG`.
> util: disable leaked handles warning by default

- src/backend/hip/pup/yaksuri_hipi_get_ptr_attr.c
- src/backend/hip/subconfigure.m4
- test/pack/pack-hip.c
ROCM 6.0.0 changed the field name from `memoryType` to `type`. Thus we need configure check and adapt the code.
> hip: add configure check for hipPointerAttribute_t.memoryType

- src/backend/hip/pup/yaksuri_hipi_get_ptr_attr.c
- src/backend/ze/genpup.py
- src/util/yaksu_handle_pool.c
- src/util/yaksu_handle_pool.h
- test/pack/pack-common.h
- test/pack/pack-hip.c
Handle hipPointerGetAttributes changes from ROCm 6. Now there are
explicit enum values for managed and unregistered host types. See
https://github.com/pmodels/mpich/pull/7075 for initial changes in MPICH.
Fix support for ROCm versions >= 6.
> backend/hip: Update pointer attributes query

- src/backend/hip/pup/yaksuri_hipi_get_ptr_attr.c
[6a1c2611a] broke compilation for older ROCm versions. I forgot to test with an older ROCm module before merge.
> backend/hip: Fix compilation for ROCm < 6

- configure.ac
- m4/aclocal_cc.m4
- m4/aclocal_check_visibility.m4
- m4/aclocal_coverage.m4
- m4/aclocal_libs.m4
- src/backend/ze/subconfigure.m4
To suppress warnings from autoconf 2.70 and later.
Fix/suppress warnings from pgcc/nvc.
> config: update deprecated autoconf macros

- src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c
Addresses changes in the CUDA 13 runtime API. In particular, I was getting the following error when compiling MPICH 4.3.1:
`error: ‘struct cudaDeviceProp’ has no member named ‘computeMode’`
Cheers,
-Nuno
> Fix incompatibilities with CUDA 13 runtime API
